package com.sinoparasoft.enumerator;

public enum MonitorNameEnum {
	NONE, VM_CPU_UTIL, VM_DISK_READ_BYTES_RATE, VM_DISK_WRITE_BYTES_RATE, VM_MEMORY_USAGE,
	VM_NETWORK_INCOMING_BYTES_RATE, VM_NETWORK_OUTGOING_BYTES_RATE, PM_CPU_UTIL,
	/* PM_DISK_READ_BYTES_RATE, PM_DISK_WRITE_BYTES_RATE, */
	PM_MEMORY_USAGE, PM_NETWORK_INCOMING_BYTES_RATE, PM_NETWORK_OUTGOING_BYTES_RATE, CONNECTIVITY, AODH_API,
	AODH_EVALUATOR, AODH_LISTENER, AODH_NOTIFIER, CEILOMETER_API, CEILOMETER_CENTRAL, CEILOMETER_COLLECTOR,
	CEILOMETER_NOTIFICATION, CINDER_API, CINDER_SCHEDULER, CINDER_VOLUME, GLANCE_API, GLANCE_REGISTRY, KEYSTONE,
	MONGOD, NEUTRON_DHCP_AGENT, NEUTRON_L3_AGENT, NEUTRON_METADATA_AGENT, NEUTRON_OPENVSWITCH_AGENT, NEUTRON_SERVER,
	NOVA_API, NOVA_CONDUCTOR, NOVA_CONSOLEAUTH, NOVA_NOVNCPROXY, NOVA_SCHEDULER, REDIS_SERVER, CEILOMETER_COMPUTE,
	LIBVIRTD, NOVA_COMPUTE
}
