package com.sinoparasoft.enumerator;

public enum ServiceNameEnum {
	DOMAIN_MANAGEMENT, GROUP_MANAGEMENT, USER_MANAGEMENT, VIRTURAL_MACHINE_MANAGEMENT, DISK_MANAGEMENT, SNAPSHOT_MANAGEMENT, APPLICATION_TAG_MANAGEMENT, PHYSICAL_MACHINE_MANAGEMENT
}
