package com.sinoparasoft.common;

public enum AsyncOperationTypeEnum {
	CREATE_VIRTUAL_MACHINE, START_VIRTUAL_MACHINE, REBOOT_VIRTUAL_MACHINE, SHUTDOWN_VIRTUAL_MACHINE,
	DELETE_VIRTUAL_MACHINE, ATTACH_DISK, DETACH_DISK, CREATE_SNAPSHOT, DELETE_SNAPSHOT, LIVE_MIGRATION_VIRTUAL_MACHINE, CREATE_DISK, DELETE_DISK
}
