// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sinoparasoft.sdk.domain;

import com.sinoparasoft.sdk.domain.Admin;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Admin_Roo_Configurable {
    
    declare @type: Admin: @Configurable;
    
}
