// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sinosoft.model;

import com.sinosoft.model.VirtualMachineGroup;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VirtualMachineGroup_Roo_Configurable {
    
    declare @type: VirtualMachineGroup: @Configurable;
    
}
