// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sinoparasoft.model;

import com.sinoparasoft.model.PhysicalMachineType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PhysicalMachineType_Roo_Configurable {
    
    declare @type: PhysicalMachineType: @Configurable;
    
}
