// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sinoparasoft.model;

import com.sinoparasoft.model.VirtualMachine;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VirtualMachine_Roo_Configurable {
    
    declare @type: VirtualMachine: @Configurable;
    
}
