// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sinosoft.model;

import com.sinosoft.model.Monitor;
import com.sinosoft.model.MonitorDataOnDemand;
import com.sinosoft.model.MonitorIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MonitorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MonitorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MonitorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MonitorIntegrationTest: @Transactional;
    
    @Autowired
    MonitorDataOnDemand MonitorIntegrationTest.dod;
    
    @Test
    public void MonitorIntegrationTest.testCountMonitors() {
        Assert.assertNotNull("Data on demand for 'Monitor' failed to initialize correctly", dod.getRandomMonitor());
        long count = Monitor.countMonitors();
        Assert.assertTrue("Counter for 'Monitor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MonitorIntegrationTest.testFindMonitor() {
        Monitor obj = dod.getRandomMonitor();
        Assert.assertNotNull("Data on demand for 'Monitor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Monitor' failed to provide an identifier", id);
        obj = Monitor.findMonitor(id);
        Assert.assertNotNull("Find method for 'Monitor' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Monitor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MonitorIntegrationTest.testFindAllMonitors() {
        Assert.assertNotNull("Data on demand for 'Monitor' failed to initialize correctly", dod.getRandomMonitor());
        long count = Monitor.countMonitors();
        Assert.assertTrue("Too expensive to perform a find all test for 'Monitor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Monitor> result = Monitor.findAllMonitors();
        Assert.assertNotNull("Find all method for 'Monitor' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Monitor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MonitorIntegrationTest.testFindMonitorEntries() {
        Assert.assertNotNull("Data on demand for 'Monitor' failed to initialize correctly", dod.getRandomMonitor());
        long count = Monitor.countMonitors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Monitor> result = Monitor.findMonitorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Monitor' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Monitor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MonitorIntegrationTest.testFlush() {
        Monitor obj = dod.getRandomMonitor();
        Assert.assertNotNull("Data on demand for 'Monitor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Monitor' failed to provide an identifier", id);
        obj = Monitor.findMonitor(id);
        Assert.assertNotNull("Find method for 'Monitor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMonitor(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Monitor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MonitorIntegrationTest.testMergeUpdate() {
        Monitor obj = dod.getRandomMonitor();
        Assert.assertNotNull("Data on demand for 'Monitor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Monitor' failed to provide an identifier", id);
        obj = Monitor.findMonitor(id);
        boolean modified =  dod.modifyMonitor(obj);
        Integer currentVersion = obj.getVersion();
        Monitor merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Monitor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MonitorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Monitor' failed to initialize correctly", dod.getRandomMonitor());
        Monitor obj = dod.getNewTransientMonitor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Monitor' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Monitor' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Monitor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MonitorIntegrationTest.testRemove() {
        Monitor obj = dod.getRandomMonitor();
        Assert.assertNotNull("Data on demand for 'Monitor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Monitor' failed to provide an identifier", id);
        obj = Monitor.findMonitor(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Monitor' with identifier '" + id + "'", Monitor.findMonitor(id));
    }
    
}
