// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sinosoft.model;

import com.sinosoft.model.MonitorSetting;
import com.sinosoft.model.MonitorSettingDataOnDemand;
import com.sinosoft.model.MonitorSettingIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MonitorSettingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MonitorSettingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MonitorSettingIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MonitorSettingIntegrationTest: @Transactional;
    
    @Autowired
    MonitorSettingDataOnDemand MonitorSettingIntegrationTest.dod;
    
    @Test
    public void MonitorSettingIntegrationTest.testCountMonitorSettings() {
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to initialize correctly", dod.getRandomMonitorSetting());
        long count = MonitorSetting.countMonitorSettings();
        Assert.assertTrue("Counter for 'MonitorSetting' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MonitorSettingIntegrationTest.testFindMonitorSetting() {
        MonitorSetting obj = dod.getRandomMonitorSetting();
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to provide an identifier", id);
        obj = MonitorSetting.findMonitorSetting(id);
        Assert.assertNotNull("Find method for 'MonitorSetting' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MonitorSetting' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MonitorSettingIntegrationTest.testFindAllMonitorSettings() {
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to initialize correctly", dod.getRandomMonitorSetting());
        long count = MonitorSetting.countMonitorSettings();
        Assert.assertTrue("Too expensive to perform a find all test for 'MonitorSetting', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MonitorSetting> result = MonitorSetting.findAllMonitorSettings();
        Assert.assertNotNull("Find all method for 'MonitorSetting' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MonitorSetting' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MonitorSettingIntegrationTest.testFindMonitorSettingEntries() {
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to initialize correctly", dod.getRandomMonitorSetting());
        long count = MonitorSetting.countMonitorSettings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MonitorSetting> result = MonitorSetting.findMonitorSettingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MonitorSetting' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MonitorSetting' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MonitorSettingIntegrationTest.testFlush() {
        MonitorSetting obj = dod.getRandomMonitorSetting();
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to provide an identifier", id);
        obj = MonitorSetting.findMonitorSetting(id);
        Assert.assertNotNull("Find method for 'MonitorSetting' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMonitorSetting(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MonitorSetting' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MonitorSettingIntegrationTest.testMergeUpdate() {
        MonitorSetting obj = dod.getRandomMonitorSetting();
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to provide an identifier", id);
        obj = MonitorSetting.findMonitorSetting(id);
        boolean modified =  dod.modifyMonitorSetting(obj);
        Integer currentVersion = obj.getVersion();
        MonitorSetting merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MonitorSetting' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MonitorSettingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to initialize correctly", dod.getRandomMonitorSetting());
        MonitorSetting obj = dod.getNewTransientMonitorSetting(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MonitorSetting' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'MonitorSetting' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MonitorSettingIntegrationTest.testRemove() {
        MonitorSetting obj = dod.getRandomMonitorSetting();
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MonitorSetting' failed to provide an identifier", id);
        obj = MonitorSetting.findMonitorSetting(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MonitorSetting' with identifier '" + id + "'", MonitorSetting.findMonitorSetting(id));
    }
    
}
