// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sinosoft.model;

import com.sinosoft.model.PhysicalMachineLoad;
import com.sinosoft.model.PhysicalMachineLoadDataOnDemand;
import com.sinosoft.model.PhysicalMachineLoadIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PhysicalMachineLoadIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PhysicalMachineLoadIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PhysicalMachineLoadIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PhysicalMachineLoadIntegrationTest: @Transactional;
    
    @Autowired
    PhysicalMachineLoadDataOnDemand PhysicalMachineLoadIntegrationTest.dod;
    
    @Test
    public void PhysicalMachineLoadIntegrationTest.testCountPhysicalMachineLoads() {
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to initialize correctly", dod.getRandomPhysicalMachineLoad());
        long count = PhysicalMachineLoad.countPhysicalMachineLoads();
        Assert.assertTrue("Counter for 'PhysicalMachineLoad' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PhysicalMachineLoadIntegrationTest.testFindPhysicalMachineLoad() {
        PhysicalMachineLoad obj = dod.getRandomPhysicalMachineLoad();
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to provide an identifier", id);
        obj = PhysicalMachineLoad.findPhysicalMachineLoad(id);
        Assert.assertNotNull("Find method for 'PhysicalMachineLoad' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PhysicalMachineLoad' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PhysicalMachineLoadIntegrationTest.testFindAllPhysicalMachineLoads() {
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to initialize correctly", dod.getRandomPhysicalMachineLoad());
        long count = PhysicalMachineLoad.countPhysicalMachineLoads();
        Assert.assertTrue("Too expensive to perform a find all test for 'PhysicalMachineLoad', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PhysicalMachineLoad> result = PhysicalMachineLoad.findAllPhysicalMachineLoads();
        Assert.assertNotNull("Find all method for 'PhysicalMachineLoad' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PhysicalMachineLoad' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PhysicalMachineLoadIntegrationTest.testFindPhysicalMachineLoadEntries() {
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to initialize correctly", dod.getRandomPhysicalMachineLoad());
        long count = PhysicalMachineLoad.countPhysicalMachineLoads();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PhysicalMachineLoad> result = PhysicalMachineLoad.findPhysicalMachineLoadEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PhysicalMachineLoad' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PhysicalMachineLoad' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PhysicalMachineLoadIntegrationTest.testFlush() {
        PhysicalMachineLoad obj = dod.getRandomPhysicalMachineLoad();
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to provide an identifier", id);
        obj = PhysicalMachineLoad.findPhysicalMachineLoad(id);
        Assert.assertNotNull("Find method for 'PhysicalMachineLoad' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPhysicalMachineLoad(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PhysicalMachineLoad' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhysicalMachineLoadIntegrationTest.testMergeUpdate() {
        PhysicalMachineLoad obj = dod.getRandomPhysicalMachineLoad();
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to provide an identifier", id);
        obj = PhysicalMachineLoad.findPhysicalMachineLoad(id);
        boolean modified =  dod.modifyPhysicalMachineLoad(obj);
        Integer currentVersion = obj.getVersion();
        PhysicalMachineLoad merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PhysicalMachineLoad' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhysicalMachineLoadIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to initialize correctly", dod.getRandomPhysicalMachineLoad());
        PhysicalMachineLoad obj = dod.getNewTransientPhysicalMachineLoad(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PhysicalMachineLoad' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PhysicalMachineLoad' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PhysicalMachineLoadIntegrationTest.testRemove() {
        PhysicalMachineLoad obj = dod.getRandomPhysicalMachineLoad();
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhysicalMachineLoad' failed to provide an identifier", id);
        obj = PhysicalMachineLoad.findPhysicalMachineLoad(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PhysicalMachineLoad' with identifier '" + id + "'", PhysicalMachineLoad.findPhysicalMachineLoad(id));
    }
    
}
