// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sinosoft.model;

import com.sinosoft.model.VirtualMachine;
import com.sinosoft.model.VirtualMachineDataOnDemand;
import com.sinosoft.model.VirtualMachineIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VirtualMachineIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VirtualMachineIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VirtualMachineIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VirtualMachineIntegrationTest: @Transactional;
    
    @Autowired
    VirtualMachineDataOnDemand VirtualMachineIntegrationTest.dod;
    
    @Test
    public void VirtualMachineIntegrationTest.testCountVirtualMachines() {
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to initialize correctly", dod.getRandomVirtualMachine());
        long count = VirtualMachine.countVirtualMachines();
        Assert.assertTrue("Counter for 'VirtualMachine' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VirtualMachineIntegrationTest.testFindVirtualMachine() {
        VirtualMachine obj = dod.getRandomVirtualMachine();
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to initialize correctly", obj);
        String id = obj.getHostId();
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to provide an identifier", id);
        obj = VirtualMachine.findVirtualMachine(id);
        Assert.assertNotNull("Find method for 'VirtualMachine' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'VirtualMachine' returned the incorrect identifier", id, obj.getHostId());
    }
    
    @Test
    public void VirtualMachineIntegrationTest.testFindAllVirtualMachines() {
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to initialize correctly", dod.getRandomVirtualMachine());
        long count = VirtualMachine.countVirtualMachines();
        Assert.assertTrue("Too expensive to perform a find all test for 'VirtualMachine', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<VirtualMachine> result = VirtualMachine.findAllVirtualMachines();
        Assert.assertNotNull("Find all method for 'VirtualMachine' illegally returned null", result);
        Assert.assertTrue("Find all method for 'VirtualMachine' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VirtualMachineIntegrationTest.testFindVirtualMachineEntries() {
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to initialize correctly", dod.getRandomVirtualMachine());
        long count = VirtualMachine.countVirtualMachines();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<VirtualMachine> result = VirtualMachine.findVirtualMachineEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'VirtualMachine' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'VirtualMachine' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VirtualMachineIntegrationTest.testFlush() {
        VirtualMachine obj = dod.getRandomVirtualMachine();
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to initialize correctly", obj);
        String id = obj.getHostId();
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to provide an identifier", id);
        obj = VirtualMachine.findVirtualMachine(id);
        Assert.assertNotNull("Find method for 'VirtualMachine' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVirtualMachine(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'VirtualMachine' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VirtualMachineIntegrationTest.testMergeUpdate() {
        VirtualMachine obj = dod.getRandomVirtualMachine();
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to initialize correctly", obj);
        String id = obj.getHostId();
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to provide an identifier", id);
        obj = VirtualMachine.findVirtualMachine(id);
        boolean modified =  dod.modifyVirtualMachine(obj);
        Integer currentVersion = obj.getVersion();
        VirtualMachine merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getHostId(), id);
        Assert.assertTrue("Version for 'VirtualMachine' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VirtualMachineIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to initialize correctly", dod.getRandomVirtualMachine());
        VirtualMachine obj = dod.getNewTransientVirtualMachine(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'VirtualMachine' identifier to be null", obj.getHostId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'VirtualMachine' identifier to no longer be null", obj.getHostId());
    }
    
    @Test
    public void VirtualMachineIntegrationTest.testRemove() {
        VirtualMachine obj = dod.getRandomVirtualMachine();
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to initialize correctly", obj);
        String id = obj.getHostId();
        Assert.assertNotNull("Data on demand for 'VirtualMachine' failed to provide an identifier", id);
        obj = VirtualMachine.findVirtualMachine(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'VirtualMachine' with identifier '" + id + "'", VirtualMachine.findVirtualMachine(id));
    }
    
}
